### ISSUE TITLE
support absolute paths in windows

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline-cli-go#10] opened 2016-02-23 11:05 UTC
from @dkager:

> if you type `C:\foo\bar` it translates to `C///foo/bar`

(on a `--i-source` input port option)

**Comment by capitancambio** [comment] 2016-04-11 09:25
I can't reproduce here, this is what I get when I use an absolute path in windows 7
```
PS C:\Program Files\DAISY Pipeline 2\daisy-pipeline\cli> .\dp2.exe dtbook-to-zedai  --i-source 'C:\Program Files\DAISY Pipeline 2\daisy-pipeline\samples\dtbook\hauy_valid.xml' -o c:\tmp
Job a15c660b-9372-4e5a-a483-c8769dcd5bc8 sent to the server
(1)[INFO]       MODS file name: zedai-mods.xml
(2)[INFO]       CSS file name: zedai-css.css
(3)[INFO]       Input DTBook not in memory, loading from disk: file:/c:/Program%20Files/DAISY%20Pipeline%202/daisy-pipeline/samples/dtbook/hauy_valid.xml
(4)[INFO]       Input document version: 2005-2
(5)[INFO]       Renaming certain elements to span with @role
(6)[INFO]       Renaming code and kbd elements to reflect block or phrase variants.
(7)[INFO]       Renaming annotation elements to identify block or phrase variants.
(8)[INFO]       Convert br to lines
```

do we have more details? (cli/win version)

**Comment by josteinaj** [comment] 2016-04-11 09:58
@dkager

**Comment by dkager** [comment] 2016-04-14 08:06
With:

```
dp2.exe dtbook-to-pef --i-source "h:\test.xml" <other params>
```

I get:

```
[ERROR]      java.lang.RuntimeException: Object can not be converted to URL: h:///test.xml
```

Using single quotes it looks for the path `.\'H:\test.xml'`.

**Comment by capitancambio** [comment] 2016-04-15 17:28
I could reproduce using  ` dtbook-to-pef,` other scripts worked fine. In fact the error is thrown by  BrailleCSSTreeParser 
```
 @o.d.b.c.BrailleCSSTreeParser_CSSTreeParser:434#stylesheet
ERROR  [ o.d.p.b.css.calabash.impl.CSSInlineStep] css:inline failed   @o.d.p.b.c.c.impl.CSSInlineStep:170#run
java.lang.RuntimeException: Object can not be converted to URL: c:///Temp/dtbook/hauy_valid.xml
        at org.daisy.pipeline.braille.common.util$URLs.asURL(util.java:427) ~[na:na]
        at org.daisy.pipeline.braille.css.calabash.impl.CSSInlineStep$InlineCSSWriter.<init>(CSSInlineStep.java:242) ~[na:na]
        at org.daisy.pipeline.braille.css.calabash.impl.CSSInlineStep.run(CSSInlineStep.java:168) ~[na:na]
        at com.xmlcalabash.runtime.XAtomicStep.run(Unknown Source) ~[na:na]
        at com.xmlcalabash.runtime.XPipeline.doRun(Unknown Source) ~[na:na]
        at com.xmlcalabash.runtime.XPipeline.run(Unknown Source) ~[na:na]
        at com.xmlcalabash.runtime.XPipelineCall.run(Unknown Source) ~[na:na]
        at com.xmlcalabash.runtime.XPipeline.doRun(Unknown Source) ~[na:na]
        at com.xmlcalabash.runtime.XPipeline.run(Unknown Source) ~[na:na]
        at org.daisy.common.xproc.calabash.impl.CalabashXProcPipeline.run(CalabashXProcPipeline.java:242) ~[na:na]
        at org.daisy.pipeline.job.Job.run(Job.java:216) ~[na:na]
        at org.daisy.pipeline.job.impl.DefaultJobExecutionService$1.run(DefaultJobExecutionService.java:110) ~[na:na]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_45]
```

I don't like how the url `c:///Temp/dtbook/hauy_valid.xml` looks but it seems to work for the rest of scripts.  I'm having a deeper look

**Comment by capitancambio** [comment] 2016-04-15 17:34
It seems that URI that is what we use internally is a bit more flexible than url (what CSSTreeParser) uses. I'm going to change the client to add the file: protocol anyways.

**Comment by bertfrees** [comment] 2016-04-15 17:38
I think I should enhance my asURL function as well.

**Comment by dkager** [comment] 2016-04-15 17:44
Thanks for the feedback both!

**Comment by bertfrees** [comment] 2020-02-20 15:11
Fixed by https://github.com/daisy/pipeline-cli-go/pull/28

**Closed by bertfrees** 2020-02-20 15:11 UTC
Labels: 4 - Done, bug, eaow
